# codemagic.yaml
workflows:
  android-release:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Setup Gradle (optional but safe)
        script: |
          chmod +x ./gradlew
      - name: Build Debug APK (signed, installable)
        script: |
          ./gradlew clean
          ./gradlew assembleDebug
      - name: Verify APK existence
        script: |
          ls -la app/build/outputs/apk/debug/
    artifacts:
      - app/build/outputs/**/*.apk
