workflows:
  android-release:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_CHANNEL: stable
      flutter: stable
      xcode: latest
    scripts:
      - name: Fix Gradle Wrapper
        script: |
          cd android
          gradle wrapper --gradle-version=8.0
          chmod +x gradlew
          
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
