workflows:
  android-release:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_CHANNEL: stable
      flutter: stable
      xcode: latest
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
