workflows:
  android-release:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      android:
        java_version: 17
    scripts:
      - name: Setup Gradle
        script: |
          gradle wrapper --gradle-version=8.0
          chmod +x gradlew
          
      - name: Build APK
        script: |
          ./gradlew assembleRelease
          
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
